### ISSUE TITLE
Problems with makefile

### ISSUE THREAD

**Issue by rude0171** [refresh-bio/kmer-db#28]
Hi,
This is my first error report so please forgive any mistakes. I have been following the github code to use the program but regardless of whether I git clone the database, use conda, or download binaries I will have a fatal error appear after running "cd kmer-db && make" or using the quick-start.sh file. 

Error file is long so I have included it as a seperate file for ease of reading. [make_error.txt](https://github.com/user-attachments/files/16821296/make_error.txt) But below I have to first and last error messages. 
First error is: 
```
"In file included from src/../libs/refresh/sort/lib/pdqsort_par.h:48:
src/../libs/refresh/sort/lib/../../active_thread_pool/lib/active_thread_pool.h:88:17: error: 'notify_all' is unavailable
                        is_operating.notify_all();
                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/atomic:2526:10: note: 'notify_all' has been explicitly marked unavailable here
    void notify_all() _NOEXCEPT"
```
Last error is:

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
make: *** [src/console_all2all.o] Error 1`

Any help would be greatly appreciated, 
Sam

**Comment by agudys** [comment]
Hello! 

Clang, the default c++ compiler under macOS does not support multithreading features used by kmer-db. In order to build it, you would need to install g++ compiler. However, when using bioconda or precompiled binaries, there is no need to build anything. Just unzip the archive for your platform (https://github.com/refresh-bio/kmer-db/releases) and write ./kmer-db in the terminal.

Best,
Adam

**Comment by rude0171** [comment]
Thank you for the assistance, I've now been able to get kmer-db running. I appreciate the help.
