### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by ccrclot** [refresh-bio/kmer-db#9]
Dear developers, 
My version of Kmer-db is  1.6.2 (24.05.2019).
I am running the following command in the same directory as the KMC files and sampleTest.list:
`kmer-db build -from-kmers -f 0.1 sampleTest.list test.db`

I am getting the error 

Kmer-db version 1.6.2 (24.05.2019)
S. Deorowicz, A. Gudys, M. Dlugosz, M. Kokot, and A. Danek (c) 2018
Illegal instruction

sampleTest.list look like:
name1
name2
name3

While KMC file are:
name1.kmc_pre name1.kmc_suf
ect...

I also tried to build the database from fasta.gz file and end up on the same error.
Do you have more input about the Illegal instruction type of error?

Thanks in advance

**Comment by agudys** [comment]
Hello,
I'll take a look on that ASAP.
Regards,
Adam

**Comment by agudys** [comment]
Dear ccrclot,

Sorry for the delay. Have you used precompiled binaries? If so, I believe your problem is from the fact, that your machine does not support AVX2, while precompiled binaries use them. Please build the package on your own with NO_AVX2 switch in the makefile set to true (see the README). Let me know.

Regards,
Adam
